import {
  LayoutDashboard,
  Gavel,
  Package,
  Car,
  Brain,
  Radar,
  FileBarChart,
  CreditCard,
  User as UserIcon,
  ShieldCheck,
  Plug,
  Code2,
  Cog,
  Activity,
  History,
  Building2,
  type LucideIcon,
} from "lucide-react";
import {
  leiloes,
  lotes,
  veiculos,
  usuarios,
  pagamentos,
  assinaturas,
  connectors,
  alertas,
  jobs,
  auditoria,
  relatorios,
  organizadores,
} from "./mock";

export type Column = { key: string; label: string; format?: (v: unknown) => string };
export type FieldDef = { key: string; label: string; type?: "text" | "number" | "select" | "textarea"; options?: string[] };

export type ModuleConfig = {
  key: string;
  label: string;
  icon: LucideIcon;
  group: string;
  description: string;
  data: () => Record<string, unknown>[];
  columns: Column[];
  filters?: string[];
  fields: FieldDef[];
  searchKeys: string[];
};

const fmtMoney = (v: unknown) => `R$ ${Number(v).toLocaleString("pt-BR")}`;
const fmtPct = (v: unknown) => `${v}%`;

export const MODULES: ModuleConfig[] = [
  {
    key: "organizadores",
    label: "Organizadores",
    icon: Building2,
    group: "Operação",
    description: "Leiloeiros e instituições que organizam os leilões.",
    data: () => organizadores,
    columns: [
      { key: "nome", label: "Nome" },
      { key: "uf", label: "UF" },
      { key: "leiloes", label: "Leilões" },
      { key: "status", label: "Status" },
      { key: "contato", label: "Contato" },
    ],
    filters: ["status", "uf"],
    searchKeys: ["nome", "contato"],
    fields: [
      { key: "nome", label: "Nome" },
      { key: "uf", label: "UF" },
      { key: "contato", label: "E-mail de contato" },
      { key: "status", label: "Status", type: "select", options: ["Ativo", "Em revisão", "Inativo"] },
    ],
  },
  {
    key: "leiloes",
    label: "Leilões",
    icon: Gavel,
    group: "Operação",
    description: "Editais ativos, encerrados e agendados.",
    data: () => leiloes,
    columns: [
      { key: "numero", label: "Nº" },
      { key: "organizador", label: "Organizador" },
      { key: "tipo", label: "Tipo" },
      { key: "cidade", label: "Cidade" },
      { key: "data", label: "Data" },
      { key: "lotes", label: "Lotes" },
      { key: "status", label: "Status" },
      { key: "score", label: "Score" },
    ],
    filters: ["status", "tipo", "organizador"],
    searchKeys: ["numero", "organizador", "cidade"],
    fields: [
      { key: "numero", label: "Número do edital" },
      { key: "organizador", label: "Organizador" },
      { key: "tipo", label: "Tipo", type: "select", options: ["Judicial", "Extrajudicial", "Administrativo"] },
      { key: "cidade", label: "Cidade/UF" },
      { key: "data", label: "Data", type: "text" },
      { key: "lotes", label: "Qtd. lotes", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["Aberto", "Encerrado", "Em breve", "Cancelado"] },
    ],
  },
  {
    key: "lotes",
    label: "Lotes",
    icon: Package,
    group: "Operação",
    description: "Lotes individuais com lance, FIPE e score de oportunidade.",
    data: () => lotes,
    columns: [
      { key: "numero", label: "Lote" },
      { key: "titulo", label: "Descrição" },
      { key: "categoria", label: "Categoria" },
      { key: "lance", label: "Lance", format: fmtMoney },
      { key: "fipe", label: "FIPE", format: fmtMoney },
      { key: "desconto", label: "Desconto", format: fmtPct },
      { key: "liquidez", label: "Liquidez" },
      { key: "score", label: "Score" },
    ],
    filters: ["categoria", "liquidez"],
    searchKeys: ["titulo", "numero"],
    fields: [
      { key: "numero", label: "Número do lote" },
      { key: "titulo", label: "Descrição" },
      { key: "categoria", label: "Categoria", type: "select", options: ["Veículo leve", "Veículo pesado", "Moto", "Equipamento", "Sucata"] },
      { key: "lance", label: "Lance mínimo", type: "number" },
      { key: "fipe", label: "Tabela FIPE", type: "number" },
    ],
  },
  {
    key: "veiculos",
    label: "Veículos",
    icon: Car,
    group: "Operação",
    description: "Catálogo completo de veículos analisados.",
    data: () => veiculos,
    columns: [
      { key: "placa", label: "Placa" },
      { key: "marca", label: "Marca" },
      { key: "modelo", label: "Modelo" },
      { key: "ano", label: "Ano" },
      { key: "km", label: "KM" },
      { key: "combustivel", label: "Combustível" },
      { key: "fipe", label: "FIPE", format: fmtMoney },
      { key: "estado", label: "Estado" },
    ],
    filters: ["marca", "combustivel", "estado"],
    searchKeys: ["placa", "marca", "modelo"],
    fields: [
      { key: "placa", label: "Placa" },
      { key: "marca", label: "Marca" },
      { key: "modelo", label: "Modelo" },
      { key: "ano", label: "Ano", type: "number" },
      { key: "km", label: "Quilometragem", type: "number" },
      { key: "combustivel", label: "Combustível", type: "select", options: ["Flex", "Gasolina", "Diesel", "Híbrido", "Elétrico"] },
      { key: "estado", label: "Estado", type: "select", options: ["Bom", "Regular", "Avariado", "Sucata", "Recuperável"] },
    ],
  },
  {
    key: "inteligencia",
    label: "Inteligência",
    icon: Brain,
    group: "Inteligência",
    description: "OCR, parser e análise por IA dos editais.",
    data: () => jobs.filter((j) => j.tipo === "Parser" || j.tipo === "OCR"),
    columns: [
      { key: "tipo", label: "Pipeline" },
      { key: "alvo", label: "Alvo" },
      { key: "status", label: "Status" },
      { key: "duracao", label: "Duração (s)" },
      { key: "data", label: "Data" },
    ],
    filters: ["tipo", "status"],
    searchKeys: ["alvo"],
    fields: [
      { key: "tipo", label: "Pipeline", type: "select", options: ["Parser", "OCR"] },
      { key: "alvo", label: "Alvo" },
    ],
  },
  {
    key: "radar",
    label: "Radar",
    icon: Radar,
    group: "Inteligência",
    description: "Alertas e mudanças em editais favoritos.",
    data: () => alertas,
    columns: [
      { key: "titulo", label: "Alerta" },
      { key: "tipo", label: "Tipo" },
      { key: "severidade", label: "Severidade" },
      { key: "data", label: "Data" },
      { key: "lido", label: "Lido" },
    ],
    filters: ["tipo", "severidade"],
    searchKeys: ["titulo"],
    fields: [
      { key: "titulo", label: "Título" },
      { key: "tipo", label: "Tipo", type: "select", options: ["Edital novo", "Mudança", "Oportunidade", "Risco"] },
      { key: "severidade", label: "Severidade", type: "select", options: ["Crítico", "Alto", "Médio", "Baixo"] },
    ],
  },
  {
    key: "relatorios",
    label: "Relatórios",
    icon: FileBarChart,
    group: "Inteligência",
    description: "Exportações financeiras, operacionais e analíticas.",
    data: () => relatorios,
    columns: [
      { key: "nome", label: "Nome" },
      { key: "tipo", label: "Tipo" },
      { key: "periodo", label: "Período" },
      { key: "gerado", label: "Gerado em" },
      { key: "tamanho", label: "Tamanho" },
    ],
    filters: ["tipo"],
    searchKeys: ["nome"],
    fields: [
      { key: "nome", label: "Nome" },
      { key: "tipo", label: "Tipo", type: "select", options: ["Financeiro", "Operacional", "Usuários", "Leilões", "Veículos"] },
      { key: "periodo", label: "Período" },
    ],
  },
  {
    key: "billing",
    label: "Billing",
    icon: CreditCard,
    group: "Comercial",
    description: "Planos, assinaturas, pagamentos e faturas.",
    data: () => assinaturas,
    columns: [
      { key: "usuario", label: "Cliente" },
      { key: "plano", label: "Plano" },
      { key: "status", label: "Status" },
      { key: "mrr", label: "MRR", format: fmtMoney },
      { key: "renovacao", label: "Renovação" },
    ],
    filters: ["plano", "status"],
    searchKeys: ["usuario"],
    fields: [
      { key: "usuario", label: "Cliente" },
      { key: "plano", label: "Plano", type: "select", options: ["Starter", "Pro", "Business", "Enterprise"] },
      { key: "status", label: "Status", type: "select", options: ["Ativa", "Trial", "Cancelada", "Inadimplente"] },
      { key: "mrr", label: "MRR (R$)", type: "number" },
    ],
  },
  {
    key: "pagamentos",
    label: "Pagamentos",
    icon: CreditCard,
    group: "Comercial",
    description: "Transações, PIX, cartão e boleto.",
    data: () => pagamentos,
    columns: [
      { key: "usuario", label: "Cliente" },
      { key: "metodo", label: "Método" },
      { key: "valor", label: "Valor", format: fmtMoney },
      { key: "status", label: "Status" },
      { key: "data", label: "Data" },
    ],
    filters: ["metodo", "status"],
    searchKeys: ["usuario"],
    fields: [
      { key: "usuario", label: "Cliente" },
      { key: "metodo", label: "Método", type: "select", options: ["PIX", "Cartão", "Boleto"] },
      { key: "valor", label: "Valor (R$)", type: "number" },
    ],
  },
  {
    key: "usuarios",
    label: "Usuários",
    icon: UserIcon,
    group: "Administração",
    description: "Usuários, papéis e permissões.",
    data: () => usuarios,
    columns: [
      { key: "nome", label: "Nome" },
      { key: "email", label: "E-mail" },
      { key: "papel", label: "Papel" },
      { key: "status", label: "Status" },
      { key: "ultimoAcesso", label: "Último acesso" },
    ],
    filters: ["papel", "status"],
    searchKeys: ["nome", "email"],
    fields: [
      { key: "nome", label: "Nome" },
      { key: "email", label: "E-mail" },
      { key: "papel", label: "Papel", type: "select", options: ["Admin", "Operador", "Analista", "Convidado"] },
      { key: "status", label: "Status", type: "select", options: ["Ativo", "Inativo", "Convidado"] },
    ],
  },
  {
    key: "connectors",
    label: "Connectors",
    icon: Plug,
    group: "Plataforma",
    description: "Integrações externas com providers e health checks.",
    data: () => connectors,
    columns: [
      { key: "nome", label: "Conector" },
      { key: "provider", label: "Provider" },
      { key: "categoria", label: "Categoria" },
      { key: "status", label: "Status" },
      { key: "uptime", label: "Uptime", format: (v) => `${Number(v).toFixed(2)}%` },
      { key: "latencia", label: "Latência", format: (v) => `${v} ms` },
    ],
    filters: ["status", "categoria"],
    searchKeys: ["nome", "provider"],
    fields: [
      { key: "nome", label: "Nome" },
      { key: "provider", label: "Provider" },
      { key: "categoria", label: "Categoria" },
      { key: "status", label: "Status", type: "select", options: ["Online", "Degradado", "Offline"] },
    ],
  },
  {
    key: "developer",
    label: "Developer Center",
    icon: Code2,
    group: "Plataforma",
    description: "API keys, webhooks, tokens e logs.",
    data: () =>
      Array.from({ length: 24 }, (_, i) => ({
        id: `key-${i}`,
        nome: `key_prod_${i.toString(16).padStart(4, "0")}`,
        escopo: ["read", "write", "admin"][i % 3],
        criadoEm: `2025-${String((i % 12) + 1).padStart(2, "0")}-15`,
        ultimoUso: `há ${i + 1}d`,
        status: i % 7 === 0 ? "Revogada" : "Ativa",
      })),
    columns: [
      { key: "nome", label: "Chave" },
      { key: "escopo", label: "Escopo" },
      { key: "criadoEm", label: "Criada em" },
      { key: "ultimoUso", label: "Último uso" },
      { key: "status", label: "Status" },
    ],
    filters: ["escopo", "status"],
    searchKeys: ["nome"],
    fields: [
      { key: "nome", label: "Nome da chave" },
      { key: "escopo", label: "Escopo", type: "select", options: ["read", "write", "admin"] },
    ],
  },
  {
    key: "jobs",
    label: "Jobs",
    icon: Cog,
    group: "Plataforma",
    description: "Workers, scheduler, filas e importações.",
    data: () => jobs,
    columns: [
      { key: "tipo", label: "Tipo" },
      { key: "alvo", label: "Alvo" },
      { key: "status", label: "Status" },
      { key: "duracao", label: "Duração (s)" },
      { key: "data", label: "Data" },
    ],
    filters: ["tipo", "status"],
    searchKeys: ["alvo"],
    fields: [
      { key: "tipo", label: "Tipo", type: "select", options: ["Parser", "OCR", "Importação", "Sync"] },
      { key: "alvo", label: "Alvo" },
    ],
  },
  {
    key: "monitoring",
    label: "Monitoring",
    icon: Activity,
    group: "Plataforma",
    description: "Health, performance e logs de infraestrutura.",
    data: () =>
      [
        { servico: "API FastAPI", status: "Online", uptime: 99.98, latencia: 84 },
        { servico: "Banco Postgres", status: "Online", uptime: 99.99, latencia: 12 },
        { servico: "Redis", status: "Online", uptime: 99.95, latencia: 4 },
        { servico: "Storage S3", status: "Degradado", uptime: 98.4, latencia: 220 },
        { servico: "Workers", status: "Online", uptime: 99.7, latencia: 130 },
        { servico: "Scheduler", status: "Online", uptime: 99.9, latencia: 22 },
        { servico: "OCR Pipeline", status: "Online", uptime: 99.2, latencia: 410 },
      ].map((s, i) => ({ id: `svc-${i}`, ...s })),
    columns: [
      { key: "servico", label: "Serviço" },
      { key: "status", label: "Status" },
      { key: "uptime", label: "Uptime", format: (v) => `${v}%` },
      { key: "latencia", label: "Latência", format: (v) => `${v} ms` },
    ],
    filters: ["status"],
    searchKeys: ["servico"],
    fields: [
      { key: "servico", label: "Serviço" },
      { key: "status", label: "Status", type: "select", options: ["Online", "Degradado", "Offline"] },
    ],
  },
  {
    key: "auditoria",
    label: "Auditoria",
    icon: History,
    group: "Administração",
    description: "Histórico, eventos, alterações e usuários.",
    data: () => auditoria,
    columns: [
      { key: "ator", label: "Ator" },
      { key: "acao", label: "Ação" },
      { key: "entidade", label: "Entidade" },
      { key: "ip", label: "IP" },
      { key: "data", label: "Data" },
    ],
    filters: ["acao", "entidade"],
    searchKeys: ["ator", "ip"],
    fields: [
      { key: "ator", label: "Ator" },
      { key: "acao", label: "Ação" },
      { key: "entidade", label: "Entidade" },
    ],
  },
  {
    key: "perfil",
    label: "Perfil",
    icon: ShieldCheck,
    group: "Administração",
    description: "Dados, segurança, plano, sessões e preferências.",
    data: () => [
      { id: "p-1", item: "Dados pessoais", valor: "Atualizado", acao: "Editar" },
      { id: "p-2", item: "Segurança (2FA)", valor: "Ativada", acao: "Configurar" },
      { id: "p-3", item: "Plano atual", valor: "Business — R$ 499/mês", acao: "Alterar" },
      { id: "p-4", item: "Sessões ativas", valor: "3 dispositivos", acao: "Revisar" },
      { id: "p-5", item: "Preferências", valor: "PT-BR · Tema escuro", acao: "Editar" },
    ],
    columns: [
      { key: "item", label: "Item" },
      { key: "valor", label: "Valor" },
      { key: "acao", label: "Ação" },
    ],
    searchKeys: ["item"],
    fields: [
      { key: "item", label: "Item" },
      { key: "valor", label: "Valor" },
    ],
  },
];

export const MODULES_BY_KEY = Object.fromEntries(MODULES.map((m) => [m.key, m]));

export const NAV_GROUPS = [
  {
    label: "Visão geral",
    items: [{ key: "dashboard", label: "Dashboard", icon: LayoutDashboard }],
  },
  ...["Operação", "Inteligência", "Comercial", "Plataforma", "Administração"].map((g) => ({
    label: g,
    items: MODULES.filter((m) => m.group === g).map((m) => ({ key: m.key, label: m.label, icon: m.icon })),
  })),
];
