/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppModuleRouteImport } from './routes/app.$module'
import { Route as AppModuleIdRouteImport } from './routes/app.$module.$id'
import { Route as AppModuleIdEditRouteImport } from './routes/app.$module.$id.edit'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleIdRoute = AppModuleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppModuleRoute,
} as any)
const AppModuleIdEditRoute = AppModuleIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppModuleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$module/$id': typeof AppModuleIdRouteWithChildren
  '/app/$module/$id/edit': typeof AppModuleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/$module/$id': typeof AppModuleIdRouteWithChildren
  '/app/$module/$id/edit': typeof AppModuleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$module/$id': typeof AppModuleIdRouteWithChildren
  '/app/$module/$id/edit': typeof AppModuleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$module'
    | '/app/'
    | '/app/$module/$id'
    | '/app/$module/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$module'
    | '/app'
    | '/app/$module/$id'
    | '/app/$module/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$module'
    | '/app/'
    | '/app/$module/$id'
    | '/app/$module/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$module': {
      id: '/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$module/$id': {
      id: '/app/$module/$id'
      path: '/$id'
      fullPath: '/app/$module/$id'
      preLoaderRoute: typeof AppModuleIdRouteImport
      parentRoute: typeof AppModuleRoute
    }
    '/app/$module/$id/edit': {
      id: '/app/$module/$id/edit'
      path: '/edit'
      fullPath: '/app/$module/$id/edit'
      preLoaderRoute: typeof AppModuleIdEditRouteImport
      parentRoute: typeof AppModuleIdRoute
    }
  }
}

interface AppModuleIdRouteChildren {
  AppModuleIdEditRoute: typeof AppModuleIdEditRoute
}

const AppModuleIdRouteChildren: AppModuleIdRouteChildren = {
  AppModuleIdEditRoute: AppModuleIdEditRoute,
}

const AppModuleIdRouteWithChildren = AppModuleIdRoute._addFileChildren(
  AppModuleIdRouteChildren,
)

interface AppModuleRouteChildren {
  AppModuleIdRoute: typeof AppModuleIdRouteWithChildren
}

const AppModuleRouteChildren: AppModuleRouteChildren = {
  AppModuleIdRoute: AppModuleIdRouteWithChildren,
}

const AppModuleRouteWithChildren = AppModuleRoute._addFileChildren(
  AppModuleRouteChildren,
)

interface AppRouteChildren {
  AppModuleRoute: typeof AppModuleRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModuleRoute: AppModuleRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
