/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppVisionRouteImport } from './routes/_authenticated.app.vision'
import { Route as AuthenticatedAppUploadsRouteImport } from './routes/_authenticated.app.uploads'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated.app.perfil'
import { Route as AuthenticatedAppModuleRouteImport } from './routes/_authenticated.app.$module'
import { Route as AuthenticatedAppModuleIdRouteImport } from './routes/_authenticated.app.$module.$id'
import { Route as AuthenticatedAppModuleIdEditRouteImport } from './routes/_authenticated.app.$module.$id.edit'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVisionRoute = AuthenticatedAppVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUploadsRoute = AuthenticatedAppUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppModuleRoute = AuthenticatedAppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppModuleIdRoute =
  AuthenticatedAppModuleIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppModuleRoute,
  } as any)
const AuthenticatedAppModuleIdEditRoute =
  AuthenticatedAppModuleIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAppModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/$module': typeof AuthenticatedAppModuleRouteWithChildren
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/uploads': typeof AuthenticatedAppUploadsRoute
  '/app/vision': typeof AuthenticatedAppVisionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/$module/$id': typeof AuthenticatedAppModuleIdRouteWithChildren
  '/app/$module/$id/edit': typeof AuthenticatedAppModuleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/app/$module': typeof AuthenticatedAppModuleRouteWithChildren
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/uploads': typeof AuthenticatedAppUploadsRoute
  '/app/vision': typeof AuthenticatedAppVisionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/$module/$id': typeof AuthenticatedAppModuleIdRouteWithChildren
  '/app/$module/$id/edit': typeof AuthenticatedAppModuleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/$module': typeof AuthenticatedAppModuleRouteWithChildren
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/uploads': typeof AuthenticatedAppUploadsRoute
  '/_authenticated/app/vision': typeof AuthenticatedAppVisionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/$module/$id': typeof AuthenticatedAppModuleIdRouteWithChildren
  '/_authenticated/app/$module/$id/edit': typeof AuthenticatedAppModuleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/como-funciona'
    | '/contato'
    | '/lgpd'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/app'
    | '/app/$module'
    | '/app/perfil'
    | '/app/uploads'
    | '/app/vision'
    | '/app/'
    | '/app/$module/$id'
    | '/app/$module/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/como-funciona'
    | '/contato'
    | '/lgpd'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/app/$module'
    | '/app/perfil'
    | '/app/uploads'
    | '/app/vision'
    | '/app'
    | '/app/$module/$id'
    | '/app/$module/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/auth'
    | '/como-funciona'
    | '/contato'
    | '/lgpd'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/_authenticated/app'
    | '/_authenticated/app/$module'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/uploads'
    | '/_authenticated/app/vision'
    | '/_authenticated/app/'
    | '/_authenticated/app/$module/$id'
    | '/_authenticated/app/$module/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  AuthRoute: typeof AuthRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  LgpdRoute: typeof LgpdRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vision': {
      id: '/_authenticated/app/vision'
      path: '/vision'
      fullPath: '/app/vision'
      preLoaderRoute: typeof AuthenticatedAppVisionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/uploads': {
      id: '/_authenticated/app/uploads'
      path: '/uploads'
      fullPath: '/app/uploads'
      preLoaderRoute: typeof AuthenticatedAppUploadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/$module': {
      id: '/_authenticated/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AuthenticatedAppModuleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/$module/$id': {
      id: '/_authenticated/app/$module/$id'
      path: '/$id'
      fullPath: '/app/$module/$id'
      preLoaderRoute: typeof AuthenticatedAppModuleIdRouteImport
      parentRoute: typeof AuthenticatedAppModuleRoute
    }
    '/_authenticated/app/$module/$id/edit': {
      id: '/_authenticated/app/$module/$id/edit'
      path: '/edit'
      fullPath: '/app/$module/$id/edit'
      preLoaderRoute: typeof AuthenticatedAppModuleIdEditRouteImport
      parentRoute: typeof AuthenticatedAppModuleIdRoute
    }
  }
}

interface AuthenticatedAppModuleIdRouteChildren {
  AuthenticatedAppModuleIdEditRoute: typeof AuthenticatedAppModuleIdEditRoute
}

const AuthenticatedAppModuleIdRouteChildren: AuthenticatedAppModuleIdRouteChildren =
  {
    AuthenticatedAppModuleIdEditRoute: AuthenticatedAppModuleIdEditRoute,
  }

const AuthenticatedAppModuleIdRouteWithChildren =
  AuthenticatedAppModuleIdRoute._addFileChildren(
    AuthenticatedAppModuleIdRouteChildren,
  )

interface AuthenticatedAppModuleRouteChildren {
  AuthenticatedAppModuleIdRoute: typeof AuthenticatedAppModuleIdRouteWithChildren
}

const AuthenticatedAppModuleRouteChildren: AuthenticatedAppModuleRouteChildren =
  {
    AuthenticatedAppModuleIdRoute: AuthenticatedAppModuleIdRouteWithChildren,
  }

const AuthenticatedAppModuleRouteWithChildren =
  AuthenticatedAppModuleRoute._addFileChildren(
    AuthenticatedAppModuleRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppModuleRoute: typeof AuthenticatedAppModuleRouteWithChildren
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppUploadsRoute: typeof AuthenticatedAppUploadsRoute
  AuthenticatedAppVisionRoute: typeof AuthenticatedAppVisionRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppModuleRoute: AuthenticatedAppModuleRouteWithChildren,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppUploadsRoute: AuthenticatedAppUploadsRoute,
  AuthenticatedAppVisionRoute: AuthenticatedAppVisionRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AjudaRoute: AjudaRoute,
  AuthRoute: AuthRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  LgpdRoute: LgpdRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
