/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppModuleRouteImport } from './routes/_authenticated.app.$module'
import { Route as AuthenticatedAppModuleIdRouteImport } from './routes/_authenticated.app.$module.$id'
import { Route as AuthenticatedAppModuleIdEditRouteImport } from './routes/_authenticated.app.$module.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppModuleRoute = AuthenticatedAppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppModuleIdRoute =
  AuthenticatedAppModuleIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppModuleRoute,
  } as any)
const AuthenticatedAppModuleIdEditRoute =
  AuthenticatedAppModuleIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAppModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/$module': typeof AuthenticatedAppModuleRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/$module/$id': typeof AuthenticatedAppModuleIdRouteWithChildren
  '/app/$module/$id/edit': typeof AuthenticatedAppModuleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/$module': typeof AuthenticatedAppModuleRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/$module/$id': typeof AuthenticatedAppModuleIdRouteWithChildren
  '/app/$module/$id/edit': typeof AuthenticatedAppModuleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/$module': typeof AuthenticatedAppModuleRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/$module/$id': typeof AuthenticatedAppModuleIdRouteWithChildren
  '/_authenticated/app/$module/$id/edit': typeof AuthenticatedAppModuleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/$module'
    | '/app/'
    | '/app/$module/$id'
    | '/app/$module/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/$module'
    | '/app'
    | '/app/$module/$id'
    | '/app/$module/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/$module'
    | '/_authenticated/app/'
    | '/_authenticated/app/$module/$id'
    | '/_authenticated/app/$module/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/$module': {
      id: '/_authenticated/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AuthenticatedAppModuleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/$module/$id': {
      id: '/_authenticated/app/$module/$id'
      path: '/$id'
      fullPath: '/app/$module/$id'
      preLoaderRoute: typeof AuthenticatedAppModuleIdRouteImport
      parentRoute: typeof AuthenticatedAppModuleRoute
    }
    '/_authenticated/app/$module/$id/edit': {
      id: '/_authenticated/app/$module/$id/edit'
      path: '/edit'
      fullPath: '/app/$module/$id/edit'
      preLoaderRoute: typeof AuthenticatedAppModuleIdEditRouteImport
      parentRoute: typeof AuthenticatedAppModuleIdRoute
    }
  }
}

interface AuthenticatedAppModuleIdRouteChildren {
  AuthenticatedAppModuleIdEditRoute: typeof AuthenticatedAppModuleIdEditRoute
}

const AuthenticatedAppModuleIdRouteChildren: AuthenticatedAppModuleIdRouteChildren =
  {
    AuthenticatedAppModuleIdEditRoute: AuthenticatedAppModuleIdEditRoute,
  }

const AuthenticatedAppModuleIdRouteWithChildren =
  AuthenticatedAppModuleIdRoute._addFileChildren(
    AuthenticatedAppModuleIdRouteChildren,
  )

interface AuthenticatedAppModuleRouteChildren {
  AuthenticatedAppModuleIdRoute: typeof AuthenticatedAppModuleIdRouteWithChildren
}

const AuthenticatedAppModuleRouteChildren: AuthenticatedAppModuleRouteChildren =
  {
    AuthenticatedAppModuleIdRoute: AuthenticatedAppModuleIdRouteWithChildren,
  }

const AuthenticatedAppModuleRouteWithChildren =
  AuthenticatedAppModuleRoute._addFileChildren(
    AuthenticatedAppModuleRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppModuleRoute: typeof AuthenticatedAppModuleRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppModuleRoute: AuthenticatedAppModuleRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
